### ISSUE TITLE
issue-67 MorphoBr

### ISSUE THREAD

**Issue by analununes** [cpdoc/test#16]
No commit a54e7d0cb7eb6012fa8dbe88dcdbc3a3736e6e95 acredito ter finalizado a estrutura (trie) para o MorphoBr.
No commit 8a3ce4fad35c5bff54935f78103a39a28d1bd311 criei uma função que anota em um novo conllu (no campo _deps) as classificações do MorphoBr para adjetivos, adverbios, nomes e verbos.

Os próximos passos são:

- criar uma função para fazer anotações em vários arquivos de uma só vez

- criar uma função para comparar as anotações e retornar erros de classificação

**Comment by arademaker** [comment]
@analununes no ultimo commit do dhbb-nlp, coloquei o `src/morphobr.lisp` que faz quase tudo que queremos fazer. 

<img width="1637" alt="image" src="https://user-images.githubusercontent.com/86403/116443489-19cead00-a82a-11eb-9e87-fe77545295a9.png">

O output não está elegante, mas basicamente a idéia está lá. veja agora que temos que usar o campo `feats` dos conllu para refinar a função `compatible` que compara token com uma entrada do dicionário. Na figura, `tenentistas` foi encontrado no dicionario com duas entradas, mas não é um caso de ambiguidade, apenas o fato de termos o Masc e Fem como entradas diferentes no dicionário para uma palavra sem gênero definido. Mas `irrompida` não foi localizada. 

Também temos casos como:

```
#<TOKEN "Anistiado" VERB #1-acl-5> not found in dict
```

Que pode ser tanto verbo quanto adjetivo:

```
% rg ^anistiado ~/work/morpho-br/verbs/*
/Users/ar/work/morpho-br/verbs/verbs-aae.dict
24326:anistiado	anistiar+V+PTPASS+M+SG
24327:anistiados	anistiar+V+PTPASS+M+PL
ar@leme dhbb-nlp % rg ^anistiado ~/work/morpho-br/adjectives
/Users/ar/work/morpho-br/adjectives/adjectives-aa.dict
17460:anistiado	anistiado+A+M+SG
17461:anistiados	anistiado+A+M+PL
```

**Comment by arademaker** [comment]
melhorei saida um pouco:

```
#<TOKEN "nacional" ADJ Gender=Masc|Number=Sing #5-amod-4> ambiguos, found (#<ENTRY <nacional:nacional | A A+M+SG>>
                                                                           #<ENTRY <nacional:nacional | A A+F+SG>>)

```

Agora podemos ir aprimorando a lógica a medida que olhamos para os dados e mismatches.

**Comment by arademaker** [comment]
@leoalenc você poderia nos ajudar aqui talvez?

**Comment by leoalenc** [comment]
> @leoalenc você poderia nos ajudar aqui talvez?

@arademaker, vou ver o que posso fazer. Precisaria primeiro me inteirar da problemática. Ainda não me está claro o que pretendem fazer.

**Comment by analununes** [comment]
@arademaker  eu acreditava estar perto de terminar as funções de comparação mas surgiu um problema com o encoding do conllu e não consigo testar em vários arquivos. 
Eu não entendi muito bem, vamos trocar as implementações em haskell por essa em lisp?

**Comment by arademaker** [comment]
Do ponto de vista da tarefa, o código Lisp está quase pronto, podemos usa-lo antes de terminar o código Haskell, a final, pelo visto vou ter que te ajudar com o Haskell.

**Comment by arademaker** [comment]
acho que podemos combinar uma seção de trabalho amanhã talvez...

**Comment by analununes** [comment]
acho uma boa ideia! Posso em qulaquer horario a tarde ou a noite

**Comment by arademaker** [comment]
alguns casos podem precisar da analise sintática:

```
#<TOKEN "entender"/"entender" VERB/VerbForm=Inf #5-xcomp-4> ambiguos, found (#<ENTRY entender:entender | V V+SBJF+3+SG>
                                                                             #<ENTRY entender:entender | V V+SBJF+1+SG>
                                                                             #<ENTRY entender:entender | V V+INF+3+SG>
                                                                             #<ENTRY entender:entender | V V+INF+1+SG>
                                                                             #<ENTRY entender:entender | V V+INF>)
```

infinitivo xcomp a conjugacao está no verbo principal... então seria ultima entrada do morpho-br acima.

**Comment by analununes** [comment]
@arademaker No commit 55666b0b14288e9ce38de8af787ceafac10dbab9 criei uma nova função para comparar as classificações. Nessa implementação os arquivos são conferidos sem escrever as informações do MorphoBr nos arquivos Conllu, o que resolve o problema anterior! 
A saída atual da função é assim:


"Processing 161.conllu  error on partir: partir+n options: partir+v+inf, partir+v+inf+1+sg, partir+v+inf+3+sg, partir+v+sbjf+1+sg, partir+v+sbjf+3+sg |  error on partir: partir+n options: partir+v+inf, partir+v+inf+1+sg, partir+v+inf+3+sg, partir+v+sbjf+1+sg, partir+v+sbjf+3+sg |  error on atuado: atuar+v+ptpass options: atuar+v+ptpass+m+sg |  error on fazendas: fazendas+n+f+pl options: fazenda+n+f+pl |  error on cana-de-a\231\250car: cana-de-a\231\250car+v+inf options: cana-de-a\231\250car+n+f+sg |  error on aceita: aceitar+v+ptpass+f+sg options: aceitar+v+imp+2+sg, aceitar+v+prs+3+sg, aceito+a+f+sg |  error on rendas: rendas+n+f+pl options: rendar+v+prs+2+sg, render+v+imp+2+sg, render+v+sbjr+2+sg, renda+n+f+pl |  error on Casou: Casar+v+prf+3+sg options: casar+v+prf+3+sg | "
"Processing 166.conllu  error on estudante: estudante+n+u+sg options: estudante+n+f+sg, estudante+n+m+sg |  error on Irrompida: Irrompido+v+ptpass+f+sg options: irromper+v+ptpass+f+sg |  error on envolvido: envolver+v+ptpass options: envolver+v+ptpass+m+sg, envolvido+a+m+sg |  error on Realengo: Realengo+n+m+sg options: realengo+n+m+sg, realengo+a+m+sg |  error on segundo-tenente: segundo-tenente+n+f+sg options: not found |  error on primeiro-tenente: primeiro-tenente+n+f+sg options: not found |  error on capit\227o: capit\227o+n+f+sg options: capit\227o+n+m+sg |  error on Anistiado: Anistiado+v+ptpass+m+sg options: anistiar+v+ptpass+m+sg, anistiado+a+m+sg | "
"Processing 172.conllu  error on eleger: eleger+n+m+sg options: eleger+v+inf, eleger+v+inf+1+sg, eleger+v+inf+3+sg, eleger+v+sbjf+1+sg, eleger+v+sbjf+3+sg |  error on deputado: deputar+n+m+sg options: deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg |  error on Reeleito: reeleito+v+ptpass+m+sg options: reeleger+v+ptpass+m+sg, reeleito+n+m+sg, reeleito+a+m+sg |  error on ga\250cho: ga\250char+a+m+sg options: ga\250cho+n+m+sg, ga\250cho+a+m+sg |  error on vinculado: vinculado+v+ptpass+m+sg options: vincular+v+ptpass+m+sg, vinculado+a+m+sg |  error on C\226mara: C\226mara+n+f+sg options: c\226mara+n+f+sg, c\226mara+n+m+sg |  error on diversos: diversos+a+m+pl options: diverso+a+m+pl |  error on n\186: n\186+n+m+sg options: not found |  error on Divorciado: Divorciado+v+ptpass+m+sg options: divorciar+v+ptpass+m+sg, divorciado+a+m+sg |  error on n\250pcias: n\250pcia+a+f+pl options: n\250pcia+n+f+pl, n\250pcias+n+f+pl | "

**Comment by arademaker** [comment]
@analununes vejo alguns problemas que podem explicar sua performance ruim e problema de memória. Veja que no meu código Lisp, leio os arquivos do morpho-br um por vez, abro o arquivo, atualizado uma hash table e fecho o arquivo antes de passar para o próximo.  No seu código, vc parece ler todos os arquivos https://github.com/cpdoc/test/blob/issue-67/src/MorphoBr.hs#L67-L70 antes de construir a estrutura de dados... veja que no Lisp, uso a função directory que no Haskell seria https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#v:listDirectory.

**Comment by arademaker** [comment]
O formato do report deve ser o mais parecido possível com o formato que produzo do Lisp... e a lógica pode ser como está no Lisp por agora. @leoalenc e eu estamos pensando em como refinar a comparação dos tokens com as entradas e o que constituirá uma situação a ser listada como possível erro no report.

**Comment by leoalenc** [comment]
> O formato do report deve ser o mais parecido possível com o formato que produzo do Lisp... e a lógica pode ser como está no Lisp por agora. @leoalenc e eu estamos pensando em como refinar a comparação dos tokens com as entradas e o que constituirá uma situação a ser listada como possível erro no report.

@arademaker, sim, estou trabalhando nisso. Usando o conhecimento sobre a estrutura morfossintática do português, poderei, em breve, listar todos os casos que não constituem verdadeiras discrepâncias por decorrerem de redundâncias no MorphoBr, por exemplo, oito entradas para a forma _simples_, quatro como adjetivo e quatro como substantivo.

**Comment by analununes** [comment]
@leoalenc, criei essa tabela olhando a documentação do MorphoBr e procurando uma equivalência em UD. Você pode conferir se está certo ou sugerir alguma alteração?
`

  | MorphoBr | VerbForm | Mood | Tense | Voice
-- | -- | -- | -- | -- | --
infinitive | INF | Inf |   |   |  
gerund | GRD | Ger |   |   |  
passive participle | PTPASS | Part |   |   | Pass
present indicative | PRS | Fin | Ind | Pres |  
imperfect indicative | IMPF | Fin | Ind | Imp |  
perfect indicative | PRF | Fin | Ind | Past |  
future indicative | FUT | Fin | Ind | Fut |  
plusquamperfect indicative | PQP | Fin | Ind | Pqp |  
present subjunctive | SBJR | Fin | Sub | Pres |  
imperfect subjunctive | SBJP | Fin | Sub | Imp |  
future subjunctive | SBJF | Fin | Sub | Fut |  
imperative | IMP | Fin | Imp |   |  
conditional | COND | Fin | Cod |   |  

`

**Comment by leoalenc** [comment]
> @leoalenc, criei essa tabela olhando a documentação do MorphoBr e procurando uma equivalência em UD. Você pode conferir se está certo ou sugerir alguma alteração?
> `
> 
>  	MorphoBr	VerbForm	Mood	Tense	Voice
> infinitive	INF	Inf	 	 	 
> gerund	GRD	Ger	 	 	 
> passive participle	PTPASS	Part	 	 	Pass
> present indicative	PRS	Fin	Ind	Pres	 
> imperfect indicative	IMPF	Fin	Ind	Imp	 
> perfect indicative	PRF	Fin	Ind	Past	 
> future indicative	FUT	Fin	Ind	Fut	 
> plusquamperfect indicative	PQP	Fin	Ind	Pqp	 
> present subjunctive	SBJR	Fin	Sub	Pres	 
> imperfect subjunctive	SBJP	Fin	Sub	Imp	 
> future subjunctive	SBJF	Fin	Sub	Fut	 
> imperative	IMP	Fin	Imp	 	 
> conditional	COND	Fin	Cod	 	 
> `

@analununes e @arademaker, o único problema é PTPASS, conforme esta [_issue_](https://github.com/LR-POR/tutorial/issues/1). Deveríamos ter PTPST, que passa a ser equivalente a [VerbForm:Part](https://universaldependencies.org/u/feat/all.html#Part).

**Comment by leoalenc** [comment]
> @leoalenc você poderia nos ajudar aqui talvez?

@arademaker, fiz, com o script abaixo, um processamento do relatório de modo a extrair os  tokens com suas respectivas análises. Veja os demais anexos. A lista not_found.uniq.txt mostra tanto os itens irrelevantes (expressões numéricas etc.) para uma atualização do MorphoBr quanto os relevantes.

```
#! /bin/bash
# This script first edits the report file, so that each sentence with its analysis occupies 
# a single line. It then extracts the list of tokens with the corresponding analyses.
# Finally, the word and lemma pairs not found in the dictionary are extracted and counted.
# leonel.de.alencar@ufc.br

tr "\n" "@" < report-morpho-bosque.txt |  sed "s/@@@/}}/g" \
| sed "s/@@/{/g" \
| sed "s/@/§/g" | tr "}" "\n" | sed "s@§#<TOKEN@{#<TOKEN@g" > report.edt.txt  

grep -E "#<TOKEN" report.edt.txt | awk -F{ '{for(i=2;i<=NF;i++) print $i}' > list_of_tokens.txt

grep -E "not found in dict" list_of_tokens.txt > not_found.txt

awk '{print $2}' not_found.txt | tr -d "[\"]" | awk -F/ '{print $1, $2}' | sort | uniq -c > not_found.uniq.txt
```
[not_found.uniq.txt](https://github.com/cpdoc/test/files/6430249/not_found.uniq.txt)

**Comment by arademaker** [comment]
oi @leoalenc , como este report foi gerado por um código meu, eu poderia adaptar diretamente para listar apenas os casos de not found.  Sim, parecem ter muitos casos para serem avaliados no morphobr e/ou casos onde a analise do parser está errada (mais provável). a questão é como sistematizar esta verificação para acrescentar o que for necessário no morpho-br e corrigir o que tiver que ser corrigido nos conllu.

**Comment by leoalenc** [comment]
@arademaker, pelo menos 55 casos de _not found in dict_ devem-se a diminutivos. Muitas dessas formas, contudo, constam do MorphoBr, porém, neste é dada como lema a forma de base. Comparemos:

> #<TOKEN "macaquinho"/"macaquinho" NOUN/Gender=Masc|Number=Sing #25-obj-22> not found in dict
> #<TOKEN "pobrezinhos"/"pobrezinho" NOUN/Gender=Masc|Number=Plur #10-nmod-7> not found in dict
> #<TOKEN "mãezinhas"/"mãezinha" NOUN/Gender=Fem|Number=Plur #11-nmod-8> not found in dict

 
`grep -Ew "^(macaquinho|pobrezinhos|mãezinhas)" nouns/*.dict adjectives/*.dict`

> nouns/nouns-ac.dict:macaquinho	macaco+N+DIM+M+SG
> nouns/nouns-ac.dict:mãezinhas	mãe+N+DIM+F+PL
> nouns/nouns-ac.dict:mãezinhas	pai+N+DIM+F+PL
> nouns/nouns-ac.dict:pobrezinhos	pobre+N+DIM+M+PL
> adjectives/adjectives-ad.dict:pobrezinhos	pobre+A+DIM+M+PL

O mesmo problema ocorrerá certamente com os aumentativos.

**Comment by leoalenc** [comment]
> oi @leoalenc , como este report foi gerado por um código meu, eu poderia adaptar diretamente para listar apenas os casos de not found. Sim, parecem ter muitos casos para serem avaliados no morphobr e/ou casos onde a analise do parser está errada (mais provável). a questão é como sistematizar esta verificação para acrescentar o que for necessário no morpho-br e corrigir o que tiver que ser corrigido nos conllu.

@arademaker, acho que todas as informações são úteis. Precisei gerar o relatório noutro formato, com uma sentença por linha, junto com _tokens_ e _entries_  separados por separadores diferentes, para poder usar o awk e outras ferramentas com mais facilidade (para mim). Portanto, o formato pode continuar o atual, que eu converto aqui. Seja como for, vou descobrindo muitos casos interessantes que contribuem para uma melhora de ambos os recursos.

**Comment by arademaker** [comment]
Correto, e queremos uma convergência, então nestes casos, queremos corrigir os corpora PT. Em https://github.com/cpdoc/dhbb-nlp/blob/master/src/morphobr.lisp#L72-L89, eu comparo entradas do morph-br com tokens usando form/lemma/POS. Precisamos repensar a estratégia, talvez em um meeting, pelo visto precisamos buscar apenas a pelo campo form do token no dicionário e trazer todas as entradas possíveis para a form. com isso, poderão ocorrer vários casos:

1. a form tem uma única entrada no morphobr 
  1. a entrada tem lemma/pos iguais ao token
  2. a entrada tem lemma igual ao token e POS diferente
  3. a entrada em POS igual ao token e lemma diferente
2. a form tem mais de uma analise
  1. uma ou mais entrada tem lemma/pos igual ao token
  2. uma ou mais entradas tem lemma igual ao token mas POS diferentes
  3. uma ou mais entradas tem POS igual ao token mas lemas são diferentes
  4. nenhuma entrada tem lemma ou POS iguais ao token

Seria isso? E para cada caso temos que ter uma possível ação...

**Comment by arademaker** [comment]
Com 

``` 
% awk '$2 ~ /inho$/ {print $2,$3,$4}' *.conllu | sort | uniq -c | sort -nr
...
   1 jatinho jatinho NOUN
   1 churrasquinho churrasquinho NOUN
   1 chorinho chorinho NOUN
   1 certinho certinho ADJ
   1 Acabadinho acabar VERB
...
``

**Comment by arademaker** [comment]
> Precisei gerar o relatório noutro formato

Sim, só disse que se vc precisar, eu posso gerar o relatório de outra forma, alterando poucas linhas do código e produzindo o formato que for mais flexível para vc processar. Eu posso produzir o seu `list_of_tokens.txt` diretamente se te ajudar.

**Comment by leoalenc** [comment]
> > Precisei gerar o relatório noutro formato
> 
>  Eu posso produzir o seu `list_of_tokens.txt` diretamente se te ajudar.
@arademaker, seria útil isso. Eu vejos que os dados se estruturam da seguinte forma:

```
sentence_1 token_1 entry_1.1 entry_1.2 ... entry_1.n token_2 entry_2.1 entry_2.2 ... entry_2.n ... token_m entry_m_1 ... entry_m.n

sentence_2 ... token_1 entry_1.1 entry_1.2 ... entry_1.n token_2 entry_2.1 entry_2.2 ... entry_2.n ... token_m entry_m_1 ... entry_m.n

```
Ou seja, para cada sentença, tenho um certo número de tokens, a cada um dos quais corresponde um certo número de _entries_. eu preciso saber se há "compatibilidade" entre a _entry_ tal de um certo token de uma certa sentença. Por isso, me pareceu mais natural agrupar as sentenças da forma acima.  
Uma opção mais sofisticada e menos _ad hoc_ seria gerar um xml, mas, nesse caso, precisaríamos conversar ao vivo. Não sei se compensa o custo de processamento (no meu caso, em Python).

**Comment by leoalenc** [comment]
> Correto, e queremos uma convergência, então nestes casos, queremos corrigir os corpora PT. Em https://github.com/cpdoc/dhbb-nlp/blob/master/src/morphobr.lisp#L72-L89, eu comparo entradas do morph-br com tokens usando form/lemma/POS. Precisamos repensar a estratégia, talvez em um meeting, pelo visto precisamos buscar apenas a pelo campo form do token no dicionário e trazer todas as entradas possíveis para a form. com isso, poderão ocorrer vários casos:
> 
> 1. a form tem uma única entrada no morphobr
>    
>    1. a entrada tem lemma/pos iguais ao token
>    2. a entrada tem lemma igual ao token e POS diferente
>    3. a entrada em POS igual ao token e lemma diferente
> 2. a form tem mais de uma analise
>    
>    1. uma ou mais entrada tem lemma/pos igual ao token
>    2. uma ou mais entradas tem lemma igual ao token mas POS diferentes
>    3. uma ou mais entradas tem POS igual ao token mas lemas são diferentes
>    4. nenhuma entrada tem lemma ou POS iguais ao token
> 
> Seria isso? E para cada caso temos que ter uma possível ação... e na verdade isto precisa ser refinado para considerar não apenas form, lemma e pos, mas também o campo feats. E no dicionário, as entradas também não tem apenas form e lemma, mas as tags.

@arademaker, sim, precisamos conversar ao vivo.

**Comment by arademaker** [comment]
Uma outra alternativa seria usar JSON, e existem ferramentas de busca em JSON como https://stedolan.github.io/jq/. Diante do que falamos hoje, vou me focar primeiro na questão das unificações para depois discutirmos.

**Comment by analununes** [comment]
@leoalenc, o que vc acha desse formato de report? Posso fazer alterações se vc quiser


Processing 1012.conllu 
-- TOKEN deputado: deputar+n+m+sg options: deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg 
-- TOKEN mandato-tampão: mandato-tampão+n+m+sg options: not found 
-- TOKEN Constituição: Constituição+n+f+sg options: constituição+n+f+sg 
-- TOKEN votado: votar+a+m+sg options: votar+v+ptpass+m+sg, votado+a+m+sg 
-- TOKEN Licenciou: Licenciar+v+prf+3+sg options: licenciar+v+prf+3+sg 
-- TOKEN Legislativo: legislativo+n+m+sg options: legislativo+a+m+sg 
-- TOKEN válidos: váler+v+ptpass+m+pl options: válido+a+m+pl 

Processing 1020.conllu 

Processing 1043.conllu 
-- TOKEN Dizionario: Dizionario+n+m+sg options: not found 
-- TOKEN enciclopedico: enciclopedico+a+m+sg options: not found 
-- TOKEN deputado: deputar+n+m+sg options: deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg 
-- TOKEN 27ª: 27ª+a+f+sg options: not found 
-- TOKEN 28ª: 28ª+a+f+sg options: not found 
-- TOKEN 2ª: 2ª+a+f+sg options: not found 
-- TOKEN republicana: republicana+a+f+sg options: republicano+n+f+sg, republicano+a+f+sg

**Comment by leoalenc** [comment]
> @leoalenc, o que vc acha desse formato de report? Posso fazer alterações se vc quiser
> 
> 
> 
> 
> 
> Processing 1012.conllu 
> 
> -- TOKEN deputado: deputar+n+m+sg options: deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg 
> 
> -- TOKEN mandato-tampão: mandato-tampão+n+m+sg options: not found 
> 
> -- TOKEN Constituição: Constituição+n+f+sg options: constituição+n+f+sg 
> 
> -- TOKEN votado: votar+a+m+sg options: votar+v+ptpass+m+sg, votado+a+m+sg 
> 
> -- TOKEN Licenciou: Licenciar+v+prf+3+sg options: licenciar+v+prf+3+sg 
> 
> -- TOKEN Legislativo: legislativo+n+m+sg options: legislativo+a+m+sg 
> 
> -- TOKEN válidos: váler+v+ptpass+m+pl options: válido+a+m+pl 
> 
> 
> 
> Processing 1020.conllu 
> 
> 
> 
> Processing 1043.conllu 
> 
> -- TOKEN Dizionario: Dizionario+n+m+sg options: not found 
> 
> -- TOKEN enciclopedico: enciclopedico+a+m+sg options: not found 
> 
> -- TOKEN deputado: deputar+n+m+sg options: deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg 
> 
> -- TOKEN 27ª: 27ª+a+f+sg options: not found 
> 
> -- TOKEN 28ª: 28ª+a+f+sg options: not found 
> 
> -- TOKEN 2ª: 2ª+a+f+sg options: not found 
> 
> -- TOKEN republicana: republicana+a+f+sg options: republicano+n+f+sg, republicano+a+f+sg 
> 
> 

@analununes , obrigado. Vejo que você já fez a conversão do conjunto de etiquetas do Bosque para as etiquetas do morphobr. Isso é interessante, tendo em vista a ideia de comparar os dois recursos￼￼.￼ Sobre a estrutura geral do relatório￼, eu preferia a que eu sugeri.￼
￼

**Comment by arademaker** [comment]
Estamos falando ao mesmo tempo de como o programa que gera o relatório deve ser implementando, em https://github.com/LR-POR/check-tools/issues e aqui de como será o formato do relatório que ele irá produzir... talvez este issue tenha que ser migrado para lá, afinal se formos usar a lib python de unificação, mais fácil será gerar o relatório em Python. Aqui estávamos tentando fazer tudo em Haskell.

**Comment by analununes** [comment]
@leoalenc, mudei a estrutura para:
sentence_1 | token_1 : conllu_entry_1 : entry_1.1, entry_1.2 , ..., entry_1.n | token_2 : conllu_entry_2 : entry_2.1, entry_2.2, ..., entry_2.n, ... | token_m : conllu_entry_m : entry_m_1, ..., entry_m.n


Processing 1012.conllu 
Seu pai, cinco vezes deputado federal por Goiás, foi o principal defensor da criação do estado do Tocantins, que governou de 1989 a 1990 (mandato-tampão), depois entre 1995 e 1999, reelegendo-se em outubro de 1998 para mais quatro anos de mandato. | deputado : deputar+n+m+sg : deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg | mandato-tampão : mandato-tampão+n+m+sg : not found
Com a criação de Tocantins pela Constituição de 1988, através do desmembramento do norte do estado de Goiás, foram convocadas eleições gerais para o novo estado em outubro daquele ano. | Constituição : Constituição+n+f+sg : constituição+n+f+sg
Tinham mandatos de dois anos os prefeitos, vereadores, deputados estaduais e federais e o senador menos votado; e de seis anos, os dois senadores mais votados. | votado : votar+a+m+sg : votar+v+ptpass+m+sg, votado+a+m+sg
Licenciou-se do mandato em 1992 para concorrer à prefeitura de Palmas, em outubro, pela coligação União por Tocantins, encabeçada pelo PDC. | Licenciou : Licenciar+v+prf+3+sg : licenciar+v+prf+3+sg
Vitorioso, foi o primeiro prefeito da capital do novo estado, tendo sua vaga no Legislativo federal ocupada por Darci Coelho. | Legislativo : legislativo+n+m+sg : legislativo+a+m+sg
Nas eleições realizadas em outubro de 1998, obteve quase 75% dos votos válidos no estado. | válidos : váler+v+ptpass+m+pl : válido+a+m+pl

Processing 1020.conllu 

Processing 1043.conllu 
Jornalista, classificado pelo «Dizionario enciclopedico italiano» como um político nacionalista, foi fundador e diretor do periódico «Oltremare», deputado à 27ª e à 28ª legislaturas do Parlamento italiano e subsecretário das colônias de 1924 a 1926. | Dizionario : Dizionario+n+m+sg : not found | enciclopedico : enciclopedico+a+m+sg : not found | deputado : deputar+n+m+sg : deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg | 27ª : 27ª+a+f+sg : not found | 28ª : 28ª+a+f+sg : not found
No pós-guerra, foi deputado monarquista à 2ª legislatura republicana na Itália. | 2ª : 2ª+a+f+sg : not found | republicana : republicana+a+f+sg : republicano+n+f+sg, republicano+a+f+sg

**Comment by leoalenc** [comment]
> Estamos falando ao mesmo tempo de como o programa que gera o relatório deve ser implementando, em https://github.com/LR-POR/check-tools/issues e aqui de como será o formato do relatório que ele irá produzir... talvez este issue tenha que ser migrado para lá, afinal se formos usar a lib python de unificação, mais fácil será gerar o relatório em Python. Aqui estávamos tentando fazer tudo em Haskell.

@arademaker, se você achar melhor dar uma organizada geral, juntando repositórios e _issues_, por mim, tudo bem.

**Comment by leoalenc** [comment]
> @leoalenc, mudei a estrutura para:
> sentence_1 | token_1 : conllu_entry_1 : entry_1.1, entry_1.2 , ..., entry_1.n | token_2 : conllu_entry_2 : entry_2.1, entry_2.2, ..., entry_2.n, ... | token_m : conllu_entry_m : entry_m_1, ..., entry_m.n
> 
> Processing 1012.conllu
> Seu pai, cinco vezes deputado federal por Goiás, foi o principal defensor da criação do estado do Tocantins, que governou de 1989 a 1990 (mandato-tampão), depois entre 1995 e 1999, reelegendo-se em outubro de 1998 para mais quatro anos de mandato. | deputado : deputar+n+m+sg : deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg | mandato-tampão : mandato-tampão+n+m+sg : not found
> Com a criação de Tocantins pela Constituição de 1988, através do desmembramento do norte do estado de Goiás, foram convocadas eleições gerais para o novo estado em outubro daquele ano. | Constituição : Constituição+n+f+sg : constituição+n+f+sg
> Tinham mandatos de dois anos os prefeitos, vereadores, deputados estaduais e federais e o senador menos votado; e de seis anos, os dois senadores mais votados. | votado : votar+a+m+sg : votar+v+ptpass+m+sg, votado+a+m+sg
> Licenciou-se do mandato em 1992 para concorrer à prefeitura de Palmas, em outubro, pela coligação União por Tocantins, encabeçada pelo PDC. | Licenciou : Licenciar+v+prf+3+sg : licenciar+v+prf+3+sg
> Vitorioso, foi o primeiro prefeito da capital do novo estado, tendo sua vaga no Legislativo federal ocupada por Darci Coelho. | Legislativo : legislativo+n+m+sg : legislativo+a+m+sg
> Nas eleições realizadas em outubro de 1998, obteve quase 75% dos votos válidos no estado. | válidos : váler+v+ptpass+m+pl : válido+a+m+pl
> 
> Processing 1020.conllu
> 
> Processing 1043.conllu
> Jornalista, classificado pelo «Dizionario enciclopedico italiano» como um político nacionalista, foi fundador e diretor do periódico «Oltremare», deputado à 27ª e à 28ª legislaturas do Parlamento italiano e subsecretário das colônias de 1924 a 1926. | Dizionario : Dizionario+n+m+sg : not found | enciclopedico : enciclopedico+a+m+sg : not found | deputado : deputar+n+m+sg : deputar+v+ptpass+m+sg, deputado+n+m+sg, deputado+a+m+sg | 27ª : 27ª+a+f+sg : not found | 28ª : 28ª+a+f+sg : not found
> No pós-guerra, foi deputado monarquista à 2ª legislatura republicana na Itália. | 2ª : 2ª+a+f+sg : not found | republicana : republicana+a+f+sg : republicano+n+f+sg, republicano+a+f+sg

@analununes, obrigado, está bem legal. Seguindo [sugestão](https://github.com/LR-POR/check-tools/issues/1#issuecomment-835870457) de @arademaker, devemos, pelo que entendi, integrar a geração do relatório ao script em Python que verifica a unificação.

**Comment by leoalenc** [comment]
> Correto. Ana considerando que vamos usar o código NLTK , vamos tentar por agora migrar atenção para o código Python do Leonel. A ideia é tentarmos ajudar a terminar o código que le o morphobr, cria as FS e depois faz o loop sobre sentenças de conllu e seus tokens tentando unificações. Os casos sem unificações são então deportados como suspeitos de erros

@arademaker e @analununes, a versão mais recente do NLTK tem o [Universal Treebanks Version 2.0](http://www.nltk.org/nltk_data/). Deve existir um CorpusReader específico, de modo que carregar o bosque e extrair as sentenças etiquetadas seria facilitado. Infelizmente, não consegui instalar essa versão no Ubuntu 20.04 e Python 3.9. Estou trabalhando com o velho NLTK do Python2.7...

**Comment by analununes** [comment]
O objetivo agora é criar um json contendo um dicionário em que as chaves são palavras e os valores são as classificações existentes no MorphoBr. Casos em que gênero ou número são definidos por contexto ou indefinidos vão ser tratados assim: 

abadável	abadável+A+F+SG
abadável	abadável+A+M+SG

guardamos apenas:

abadável	abadável+A+SG

**Comment by arademaker** [comment]
> a versão mais recente do NLTK tem o Universal Treebanks Version 2.0. Deve existir um CorpusReader específico, de modo que carregar o bosque e extrair as sentenças etiquetadas seria facilitado. Infelizmente, não consegui instalar essa versão no Ubuntu 20.04 e Python 3.9. Estou trabalhando com o velho NLTK do Python2.7...

Este problema já resolvemos usando a https://pypi.org/project/conllu/, uma dentre as tantas libs Python para ler arquivos CoNLL-U. Mas você não conseguir rodar Python3 e o novo NLTK pode ser um problema... A versão mais nova do Ubuntu é 21.04, certo? Não daria para fazer um disc-upgrade?

**Comment by leoalenc** [comment]
> > a versão mais recente do NLTK tem o Universal Treebanks Version 2.0. Deve existir um CorpusReader específico, de modo que carregar o bosque e extrair as sentenças etiquetadas seria facilitado. Infelizmente, não consegui instalar essa versão no Ubuntu 20.04 e Python 3.9. Estou trabalhando com o velho NLTK do Python2.7...
> 
> Este problema já resolvemos usando a https://pypi.org/project/conllu/, uma dentre as tantas libs Python para ler arquivos CoNLL-U. Mas você não conseguir rodar Python3 e o novo NLTK pode ser um problema... A versão mais nova do Ubuntu é 21.04, certo? Não daria para fazer um disc-upgrade?

@arademaker, agora estou tentando instalar o NLTK 3.x.

**Comment by leoalenc** [comment]
> > > a versão mais recente do NLTK tem o Universal Treebanks Version 2.0. Deve existir um CorpusReader específico, de modo que carregar o bosque e extrair as sentenças etiquetadas seria facilitado. Infelizmente, não consegui instalar essa versão no Ubuntu 20.04 e Python 3.9. Estou trabalhando com o velho NLTK do Python2.7...
> > 
> > 
> > Este problema já resolvemos usando a https://pypi.org/project/conllu/, uma dentre as tantas libs Python para ler arquivos CoNLL-U. Mas você não conseguir rodar Python3 e o novo NLTK pode ser um problema... A versão mais nova do Ubuntu é 21.04, certo? Não daria para fazer um disc-upgrade?
> 
> @arademaker, agora estou tentando instalar o NLTK 3.x.

@arademaker , consegui, estou com nltk 3.5 e conllu.

**Comment by arademaker** [comment]
Vou fechar este issue. O problema de usar o Morpho-Br para verificação de um corpus pode ser melhor documentado como issues nos respectivos corpora. Este repo é sobre a lib Haskell. O código que @analununes terminou para simplificar o morpho-br trocando duplicatas de entradas por subspecifições de features em substantivos e adjetivos acho que encerra este issue.
