### ISSUE TITLE
comparacao jsons (wks golden vs nlu output)

### ISSUE THREAD

**Issue by arademaker** [cpdoc/test#5]
dado um json da coleção golden exportado do WKS. E dado um json saida de anotação do serviço NLU. ambos golden e anotado, sob o mesmo text file original, queremos gerar uma matrix de confusão

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/86403/109575141-00caa980-7ad0-11eb-9881-a3358ad661a6.png">

parecida com a matrix acima

**Comment by arademaker** [comment]
https://hackage.haskell.org/package/aeson

**Comment by arademaker** [comment]
O https://github.com/cpdoc/dhbb-nlp/issues/63 pode parecer vago, porque não esta claro o que é resolver o issue. Concretamente, esta tarefa trata de escrevemos um codigo para produzir a tabela acima, mas um teste de consistencia necessário, antes de tentar alinhar as anotações, é precisamente identificar se os conteúdos dos json são iguais.  Para isso, descobri um parametro extra em https://cloud.ibm.com/apidocs/natural-language-understanding#analyze, que retorna o conceúdo do RAW que submeti como entrada para produzir o JSON saida. Vejam https://github.com/cpdoc/dhbb-nlp/blob/master/ner/11262.json que agora temos no final o campo `analyzed_text`. Ou seja, podemos começar a analise comparando este campo com o valor do campo `text` nos arquivos dentro de `wks/gt/*.json`

**Comment by wellington36** [comment]
Criamos o leitor de gold json https://github.com/cpdoc/test/blob/issue-5/src/ReadGJson.hs para "wks golden", para o "nlu output" já temos o leitor https://github.com/cpdoc/test/blob/issue-6/src/NLU.hs. Agora podemos começar a buscar as diferenças.

**Comment by arademaker** [comment]
Commit 4c50fe56a5122f11ed2ba890cc1af74d41f7f851 juntou no master o código para ler o JSON golden do WKS. Agora precisamos:

1. Comparar text fields. Se um dos json não tiver o text, podemos parar o processo reportando erro. Se ambos tiverem, comparar o conteúdo e se forem iguais seguir.

2. Ordenar as mention de cada arquivo por begin. Percorrer linearmente as duas listas em paralelo. Então temos que pensar o que fazer em cada caso que aparecer. O match perfeito seria o mesmo número de mention, e todas iguais (begin, end, entity type). Listem aqui os casos que forem encontrando e vamos tentar ir definindo os critérios.

**Comment by wellington36** [comment]
No https://github.com/cpdoc/test/commit/f5005daeafd546acda84fea9ff2bad90976fd724 criamos a função que verifica se os textos são iguais.

Foi necessário alterar o json NLU em https://github.com/cpdoc/dhbb-nlp/commit/47bc4d478281cefb8b1a75e9680bcae3a911b39b, note que, o leitor que json NLU ainda não foi atualizado para essa mudança.

**Comment by analununes** [comment]
No 79a318c5a6786c40828d70b7c4274ba5ba33f39d criamos a função reading que verifica se os textos são iguais, e, caso sejam, manda os arquivos para comparação. Aqui também foram criados alguns "esqueletos" de funções que serão necessárias para realizar a comparação.

**Comment by wellington36** [comment]
No b329fe74d50ac3cdb0a5ebe375fc57ae4ec20c38 adicionamos leitura, sort (do begin (WKS) e location (NLU)) e conectamos o checkText a estrutura. Agora falta definir o que é dar "match" (quando o begin, end e a marcação coincidem) e o que fazer quando da match e quando não da.

**Comment by arademaker** [comment]
queremos produzir uma matriz e também uma lista dos casos sem match, certo? 

1. se begin/end são iguais e tipo diferente reportamos um mismatch de tipo
2. se begin/end são diferentes é um failture na identificação, caso de O (linha/coluna) da matriz acima.
3. se begin/end e tipo são iguais temos um match

**Comment by arademaker** [comment]
algum progresso hoje?

**Comment by arademaker** [comment]
para a saida final, podemos pensar em gerar um json e ter um arquivo HTML com um javascript simples para mostrar o json no browser. Talvez amanhã possamos conversar sobre isso.

**Comment by analununes** [comment]
No 3501d097cf5efd6d8e97dc98c81a10635632db85 adicionamos a função catchDiffs que retorna os matches, mismatches e failures. Ao realizar um teste com o arquivo 11262 obtivemos a seguinte mensagem: 
*** Exception: NEValidation.hs:(39,1)-(46,35): Non-exhaustive patterns in function catchDiffs 
Os próximos passos são corrigir esse problema e gerar um json dos resultados.

**Comment by analununes** [comment]
No bfa2b41fe89a4ded3043353d368651574929ced3 criamos a estrutura do JSON para fazer o report (achamos que seria uma boa ideia criar um modulo no src para essa estrutura).
Esse JSON tem uma tabela com a contagem dos casos e uma estrutura Content, onde haverá uma lista com as sentenças para cada elemento da tabela. Por exemplo, o elemento na linha "data" e coluna "data" terá uma estrutura correspondente (data_data) contendo todas as sentenças onde ocorreu esse match.

**Comment by wellington36** [comment]
No commit fbe4d3b02011bc9fa31910333c2b7424ec95baed temos a createDoc que recebe uma lista de NLU.Document, uma lista de WKS.Document e um file e cria um json. No commit ef284de1f1ac68f3cdf5efc4919c9ac3befbc6ba temos o html, js e json tal json provem da rodagem da função createDoc com todos os arquivos NLU do https://github.com/cpdoc/dhbb-nlp/tree/master/ner no commit d8cacdc09cb5ca8d5b116aaedfbbb8ed269424a0 e o html gera uma pagina web local rodando.

**Comment by wellington36** [comment]
No commit fbe4d3b temos a createDoc que recebe uma lista de NLU.Document, uma lista de WKS.Document e um file e cria um json. No https://github.com/cpdoc/dhbb-nlp/tree/NER-analysis/ner/report temos o html, js e json tal json provem da rodagem da função createDoc com todos os arquivos NLU do https://github.com/cpdoc/dhbb-nlp/tree/master/ner no commit d8cacdc09cb5ca8d5b116aaedfbbb8ed269424a0 e o html gera uma pagina web local rodando.

`python -m http.server 9999`

E cricando no link dado. 
Obs.: Ainda falta alterar a context do json gerado pela createDoc para usar uma sentença em vez de um range ao redor da marcação.

**Comment by wellington36** [comment]
Com https://github.com/cpdoc/dhbb-nlp/pull/75 e https://github.com/cpdoc/test/pull/14 acredito que já podemos fechar esse issue.

**Comment by arademaker** [comment]
ok, vc me apresenta mais tarde como usar o que foi feito e que testes vcs fizeram.

**Comment by arademaker** [comment]
interface de comando não está pronta. Vide comentarios no codigo (main) sobre como manipular no haskell PATHs (caminhos para diretórios ou arquivos no sistema operacional0.

**Comment by wellington36** [comment]
Em commit 905ef8984f4d7c57b3717dc35bc470dee9787656 adicionei a possibilidade de gerar o json via terminal:

`test-ner -t JSON_FILE NLU_PATH OUT_JSON`

**Comment by arademaker** [comment]
Já temos um pull request para o main?

**Comment by arademaker** [comment]
Pessoal, nunca façam commit no master direto!

**Comment by wellington36** [comment]
Acabei de fazer o pull.

**Comment by arademaker** [comment]
Não entendi ?! Vc já tinha modificado o master direto ... fez PR do que ?

**Comment by wellington36** [comment]
https://github.com/cpdoc/test/pulls

**Comment by wellington36** [comment]
https://github.com/cpdoc/test/tree/issue5-interface

**Comment by wellington36** [comment]
Eu não mudei o master, fiz o pull request de um branch

**Comment by wellington36** [comment]
Acredito que este issue pode ser fechado pelo commit 53289a324c023505ea6a7d27be069bdd03677e77.
